config/routes.rb
Rewsly::Application.routes.draw do
  root to: 'stories#index'
  resources :stories
  resources :categories
  resources :authors
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  post "login" => "sessions#create"
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :stories

  has_secure_password
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :stories
end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :category
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    Author.find(session[:user_id])
  end
  helper_method :current_user
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
    @stories = @author.stories
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    author = Author.find_by_email(params[:session][:email])
    if author && author.authenticate(params[:session][:password])
      session[:user_id] = author.id
      redirect_to "/"
    else
      redirect_to "/login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.author = current_user
    if @story.save
      redirect_to story_path(@story)
    else
      render :new
    end
  end

  def show
    @story = Story.find(params[:id])
    @author = @story.author
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
    if @story.update(story_params)
      redirect_to story_path(@story)
    else
      render :edit
    end
  end

  private

  def story_params
    params.require(:story).permit(:title, :body, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>
<ul>
  <% @stories.each do |story| %>
    <li><%= link_to story.title, "/stories/#{story.id}" %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<ul>
  <% @category.stories.each do |story| %>
    <li><%= link_to story.title, story_path(story) %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rewsly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h3>Categories</h3>
<ul>
  <% Category.all.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

<% if session[:user_id] %>
  <p>You are logged in as: <%= current_user.name %></p>
  <p><%= link_to "Logout", "/logout" %></p>
<% else %>
  <p><%= link_to "Login", "/login" %></p>
<% end %>

<hr>

<%= yield %>

</body>
</html>

app/views/stories/edit.html.erb
<%= simple_form_for @story do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.association :category %>
  <%= f.submit %>
<% end %>

app/views/stories/index.html.erb
<h1>Welcome to Rewsly!!</h1>

<ul>
  <% @stories.each do |story| %>
    <li><%= link_to story.title, story_path(story) %></li>
  <% end %>
</ul>

<% if session[:user_id] %>
  <%= link_to "New Story", new_story_path %>
<% end %>

app/views/stories/new.html.erb
<%= simple_form_for @story do |f| %>
  <%= f.input :title %>
  <%= f.submit %>
<% end %>

app/views/stories/show.html.erb
<h1><%= @story.title %></h1>
<% if @story.author %>
  <h2>Author: <%= link_to @story.author.name, author_path(@author) %></h2>
<% end %>
<%= @story.body %>

<p><%= link_to "Edit", edit_story_path(@story) %></p>